name: fetch
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */3 * * *'
jobs:
  fetchurl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.5.0
      - name: Install & Run
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install
          node fetchURLByAndroidV2.js
      - name: Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Commit & Push
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git add .
          git commit -m "Update by GitHub Actions" || exit 0
          git remote add gitee https://dream-deve:$GITEE_TOKEN@gitee.com/bmg369/test.git
          git push gitee main
