name: Sync GitHub to Gitee
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'  # 每3小时同步一次
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: ${{ github.event.repository.clone_url }}
          destination-repo: ${{ secrets.GITEE_REPO_URL }}
          force-push: true  # 强制推送（根据需求启用）
