name: Run Node.js Script

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.5.0'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          v1/package-lock.json
          utils/package-lock.json

    # 安装依赖
    - name: Install root dependencies
      run: npm ci

    - name: Install v1 dependencies
      working-directory: ./v1
      run: npm ci

    - name: Install utils dependencies
      working-directory: ./utils
      run: npm ci

    # 创建符号链接，使 v1/utils 指向根目录的 utils
    - name: Create symbolic link
      run: ln -s ../utils v1/utils

    # 调试步骤，列出文件结构确认路径是否正确
    - name: Debug - List project structure
      run: |
        echo "Project root:"
        ls -la
        echo "v1 directory:"
        ls -la v1/
        echo "utils directory:"
        ls -la utils/
        echo "Check if fetchList.js exists:"
        find . -name "fetchList.js" -type f
        echo "Check if symbolic link exists:"
        ls -la v1/utils/

    - name: Run Script
      working-directory: ./v1
      run: node fetchURL.js
      env:
        CUSTOM_VAR: 'value'

    - name: Commit and push changes
      if: always()
      run: |
        if ! git diff --quiet; then
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add v1/interface.txt
          git commit -m "chore: auto-update by GitHub Actions"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
