name: Run Node.js Script

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: test3911  # 明确检出到test3911目录

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.5.0'
        cache: 'npm'
        cache-dependency-path: |
          test3911/package-lock.json
          test3911/utils/package-lock.json
          test3911/v1/package-lock.json

    - name: Install dependencies
      working-directory: test3911  # 所有路径基于此目录
      run: |
        npm ci --prefix ./utils
        npm ci --prefix ./v1

    - name: Run Script
      working-directory: test3911/v1
      run: node fetchURL.js
      env:
        CUSTOM_VAR: 'value'

    - name: Commit and push changes
      if: always()
      working-directory: test3911
      run: |
        if ! git diff --quiet; then
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add v1/interface.txt
          git commit -m "chore: auto-update by GitHub Actions"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
