name: Run FetchURL Script on Node.js 21.5.0

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 21.5.0
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
          cache: 'npm'

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install npm dependencies
        run: npm ci --include=optional
        working-directory: ./v1

      - name: Run fetchURL.js script
        run: node fetchURL.js
        working-directory: ./v1
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SOME_URL: ${{ secrets.SOME_URL }}

      - name: Upload generated interface.txt
        uses: actions/upload-artifact@v4
        with:
          name: interface-file
          path: v1/interface.txt
